### ISSUE TITLE
CPU only support

### ISSUE THREAD

**Issue by jtcramer** [marl/openl3#11]
I imagine plenty of people will want to run this on machines without GPUs, and as a result will need to use the CPU-only version of tensorflow, so I think we should aim to support CPU-only installations of this package. That being said, what's the best way to handle this when people are installing via pip? Rather than creating an entirely separate PyPI repo.

**Comment by justinsalamon** [comment]
We definitely want to support CPU only. However, I think this is not an issue because we only need to specify keras as a dependency, and let the user worry about installing TF, which can be GPU or CPU. So I think as long as we specify keras as a dependency, we should be able to support GPU and CPU out of the box. 

I don't think we can test GPU execution on travis in any case: 
https://github.com/travis-ci/travis-ci/issues/5911

**Comment by jtcramer** [comment]
Good point. I'll mark this issue as closed then.
