### ISSUE TITLE
[Q] Audio chunk duration greater than 1 second

### ISSUE THREAD

**Issue by bbruhh** [marl/openl3#24]
Is there a provision to process audio chunks larger than 1 second, say 5 second audio chunks? I would imagine this will be fine. 

Can I have your opinion?

**Comment by justinsalamon** [comment]
Each embedding frame is extracted from 1 second of audio. If your audio file is longer, multiple frames will be extracted using a 1-second sliding window with a 0.1 second hop size by default (as per the [tutorial](https://openl3.readthedocs.io/en/latest/tutorial.html)). You can change the hop size if you want. 

For a 5 second audio file this means you'll get back (if you don't change any of the parameters) an array with 46 embedding frames (by default we zero-pad beginning of the signal so that the first frame is centered on time 0). In addition to the embedding array the API also returns a timestamp array which stores the timestamp corresponding to each embedding frame.
