### ISSUE TITLE
Set up Travis and Coveralls

### ISSUE THREAD

**Issue by jtcramer** [marl/openl3#6]

**Comment by justinsalamon** [comment]
We can base our travis setup script on the scaper one:

https://github.com/justinsalamon/scaper/blob/master/.travis.yml

The scaper script is extra complicated because of non-python dependencies, so our script will probably be simpler. The CREPE script is dramatically simpler but missing some things we need (e.g. coveralls), so we'll probably end up somewhere between the two:

https://github.com/marl/crepe/blob/master/.travis.yml

**Comment by justinsalamon** [comment]
We'll also need setup.cfg to automate the unit tests: https://github.com/justinsalamon/scaper/blob/master/setup.cfg
