### ISSUE TITLE
Set up readthedocs support

### ISSUE THREAD

**Issue by jtcramer** [marl/openl3#7]
Set up Sphinx, readthedocs account

**Comment by justinsalamon** [comment]
### Getting started ###

setup.py add:

extras_require={ 'docs': ['numpydoc', 'sphinx-gallery'] }

(see scaper or autopool as examples)


Follow these instructions to create initial structure:

http://docs.readthedocs.io/en/latest/getting_started.html

Things to copy over/change based on scaper’s conf.py:

imports:

import os
import sys
import six
import sphinx_rtd_theme
sys.path.insert(0, os.path.abspath('.'))
sys.path.insert(0, os.path.abspath('..’))

extensions:

extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.autosummary',
    'sphinx.ext.coverage',
    'sphinx.ext.viewcode',
    'numpydoc'
]

mock dependencies:

# Mock the dependencies
if six.PY3:
    from unittest.mock import MagicMock
else:
    from mock import Mock as MagicMock


class Mock(MagicMock):
    @classmethod
    def __getattr__(cls, name):
        return MagicMock()

MOCK_MODULES = [
    'sox', 'jams', 'scipy', 'numpy', 'pandas'
]

sys.modules.update((mod_name, Mock()) for mod_name in MOCK_MODULES)

version:

import imp
scaper_version = imp.load_source('scaper.version', '../scaper/version.py')
version = scaper_version.short_version
# The full version, including alpha/beta/rc tags.
release = scaper_version.version

theme:

html_theme = "sphinx_rtd_theme"
html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]



Link to github issues and pull requests from sphinx documentation:

source: https://github.com/sloria/sphinx-issues

Installation and Configuration

pip install sphinx-issues
Add sphinx_issues to extensions in your conf.py. If your project is on GitHub, add the issues_github_path config variable. Otherwise, use issues_uri and issues_pr_uri.
# docs/conf.py

#...
extensions = [
    #...
    'sphinx_issues',
]

# Github repo
issues_github_path = 'sloria/marshmallow'

# equivalent to
issues_uri = 'https://github.com/sloria/marshmallow/issues/{issue}'
issues_pr_uri = 'https://github.com/sloria/marshmallow/pull/{pr}'
Usage

Use the :issue: and :pr: roles in your docs like so:
See issue :issue:`42`

See issues :issue:`12,13`

See PR :pr:`58`
Use the :user: role in your docs to link to user profiles (Github by default, but can be configured via the issues_user_uri config variable).
Thanks to :user:`bitprophet` for the idea!
You can also use explicit names if you want to use a different name than the github user name:
This change is due to :user:`Andreas Mueller <amueller>`.
